[build]
  command = "chmod +x netlify-deploy.sh && ./netlify-deploy.sh"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18.18.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
